#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2024 Wewoc (github.com/wewoc)

"""
garmin_security.py

Security — sole authority over token encryption/decryption.

Responsibilities:
  - Encrypt/decrypt garmin_token.enc using AES-256-GCM
  - Store/retrieve encryption key via Windows Credential Manager (keyring)
  - clear_token() removes both the encrypted file and the WCM entry

Encryption key design:
  - User-defined on first setup (comparable to a password manager master password)
  - Stored in Windows Credential Manager under GarminLocalArchive / token_enc_key
  - Never stored in plaintext anywhere else
  - If lost: re-entry triggers re-derivation of the same AES key from the same enc_key
  - AES-256-GCM: authenticated encryption — detects file manipulation

Token format (garminconnect >= 0.2.40):
  - Library writes garmin_tokens.json to GARMIN_TOKEN_DIR during login
  - save_token() reads that file, encrypts its contents, writes garmin_token.enc
  - load_token() decrypts garmin_token.enc, writes garmin_tokens.json back so
    the library can read it directly — plaintext file removed after library login
  - Plaintext never persists on disk outside of the library login window

No GUI logic. No direct calls to garmin_api or other project modules.
"""

import json
import logging
import os
import shutil
import time
from datetime import datetime, timezone

log = logging.getLogger(__name__)

KEYRING_SERVICE  = "GarminLocalArchive"
KEYRING_ENC_USER = "token_enc_key"

# garmin_tokens.json — filename written by the garminconnect library
_TOKEN_JSON = "garmin_tokens.json"


# ══════════════════════════════════════════════════════════════════════════════
#  WCM helpers
# ══════════════════════════════════════════════════════════════════════════════

def get_enc_key_status() -> tuple[str | None, str | None]:
    """Read encryption key from Windows Credential Manager.
    Returns (key, None) on success or genuine absence, (None, error_detail) on
    a WCM read failure. Sole implementation of the WCM read — get_enc_key()
    below is a thin wrapper, kept for the five existing presence-only callers.
    """
    try:
        import keyring
        return keyring.get_password(KEYRING_SERVICE, KEYRING_ENC_USER) or None, None
    except Exception as e:
        log.warning(f"  Could not read enc_key from WCM: {e}")
        return None, str(e)


def get_enc_key() -> str | None:
    """Read encryption key from Windows Credential Manager. Returns None if not found."""
    value, _ = get_enc_key_status()
    return value


def store_enc_key(enc_key: str) -> bool:
    """Store encryption key in Windows Credential Manager. Returns True on success."""
    try:
        import keyring
        keyring.set_password(KEYRING_SERVICE, KEYRING_ENC_USER, enc_key)
        log.info("  ✓ Encryption key stored in Windows Credential Manager")
        return True
    except Exception as e:
        log.error(f"  Could not store enc_key in WCM: {e}")
        return False


def generate_enc_key() -> bool:
    """
    Generates a random 256-bit encryption key via os.urandom(32),
    encodes it as a 64-character hex string, and stores it in WCM.
    Called automatically on first setup (Path 3) — no user input required.
    Returns True on success, False if WCM storage failed.
    """
    enc_key = os.urandom(32).hex()
    return store_enc_key(enc_key)


# ══════════════════════════════════════════════════════════════════════════════
#  Crypto helpers
# ══════════════════════════════════════════════════════════════════════════════

def _derive_aes_key(enc_key: str, salt: bytes) -> bytes:
    """Derives a 32-byte AES key from the user's enc_key string via PBKDF2-HMAC-SHA256.

    salt : 16 random bytes generated by os.urandom(16) on each save.
    Stored as the first 16 bytes of garmin_token.enc and read back on load.
    """
    from cryptography.hazmat.primitives.kdf.pbkdf2 import PBKDF2HMAC
    from cryptography.hazmat.primitives import hashes

    kdf = PBKDF2HMAC(
        algorithm=hashes.SHA256(),
        length=32,
        salt=salt,
        iterations=600_000,
    )
    return kdf.derive(enc_key.encode("utf-8"))


def _clear_token_dir() -> None:
    """Removes GARMIN_TOKEN_DIR and all contents (plaintext cleanup).

    Retries up to 5 times with 1 s delay — garminconnect may hold a file
    handle on garmin_tokens.json for several seconds after login returns
    (WinError 5 on Windows).
    """
    import garmin_config as cfg
    for attempt in range(5):
        try:
            if cfg.GARMIN_TOKEN_DIR.exists():
                shutil.rmtree(cfg.GARMIN_TOKEN_DIR)
                log.debug("  Token working dir removed")
            return
        except Exception as e:
            if attempt < 4:
                log.debug(f"  Token dir removal attempt {attempt + 1} failed — retrying: {e}")
                time.sleep(1.0)
            else:
                log.warning(f"  Could not remove token working dir: {e}")


# ══════════════════════════════════════════════════════════════════════════════
#  Public API
# ══════════════════════════════════════════════════════════════════════════════

def save_token() -> bool:
    """
    Reads garmin_tokens.json from GARMIN_TOKEN_DIR (written by the library after
    SSO login), encrypts its contents with AES-256-GCM, writes garmin_token.enc.
    Removes GARMIN_TOKEN_DIR afterwards — no plaintext remains on disk.
    Reads enc_key from WCM — must already be stored before calling this.
    Returns True on success.
    """
    import garmin_config as cfg
    enc_key = get_enc_key()
    if enc_key is None:
        log.error("  Cannot save token — encryption key not found in WCM")
        return False

    token_json = cfg.GARMIN_TOKEN_DIR / _TOKEN_JSON
    if not token_json.exists():
        log.error(f"  Cannot save token — {_TOKEN_JSON} not found in token dir")
        return False

    try:
        from cryptography.hazmat.primitives.ciphers.aead import AESGCM

        plaintext  = token_json.read_bytes()
        salt       = os.urandom(16)   # 128-bit random salt, unique per save
        aes_key    = _derive_aes_key(enc_key, salt)
        nonce      = os.urandom(12)   # 96-bit nonce, standard for AES-GCM
        aesgcm     = AESGCM(aes_key)
        ciphertext = aesgcm.encrypt(nonce, plaintext, None)

        cfg.LOG_DIR.mkdir(parents=True, exist_ok=True)
        cfg.GARMIN_TOKEN_FILE.write_bytes(salt + nonce + ciphertext)
        log.info("  ✓ Token encrypted and saved")
        log_token_event("created", "sso_login")
        return True

    except Exception as e:
        log.error(f"  Token save failed: {e}")
        return False

    finally:
        _clear_token_dir()


def load_token() -> bool:
    """
    Decrypts garmin_token.enc and writes garmin_tokens.json into GARMIN_TOKEN_DIR
    so the library can read it directly via garmin.login(token_dir).
    Plaintext file is removed by _clear_token_dir() after the library has consumed it
    (called from garmin_api.py after login completes or fails).
    Returns True on success, False if: file missing, WCM empty, decryption failed.
    """
    import garmin_config as cfg
    if not cfg.GARMIN_TOKEN_FILE.exists():
        log.info("  No saved token found")
        return False

    enc_key = get_enc_key()
    if enc_key is None:
        log.warning("  Encryption key not found in WCM — re-entry required")
        return False

    try:
        from cryptography.hazmat.primitives.ciphers.aead import AESGCM

        data       = cfg.GARMIN_TOKEN_FILE.read_bytes()
        salt       = data[:16]
        nonce      = data[16:28]
        ciphertext = data[28:]
        aes_key    = _derive_aes_key(enc_key, salt)
        aesgcm     = AESGCM(aes_key)
        plaintext  = aesgcm.decrypt(nonce, ciphertext, None)

        cfg.GARMIN_TOKEN_DIR.mkdir(parents=True, exist_ok=True)
        (cfg.GARMIN_TOKEN_DIR / _TOKEN_JSON).write_bytes(plaintext)
        log.info("  ✓ Token decrypted successfully")
        return True

    except Exception as e:
        log.error(f"  Token decryption failed: {e}")
        _clear_token_dir()
        return False


def clear_token() -> bool:
    """Removes garmin_token.enc, GARMIN_TOKEN_DIR, and the enc_key from WCM.
    Returns True if both removal steps completed without error, False if
    either step failed (detail already logged at the failure site).
    """
    import garmin_config as cfg
    ok = True

    try:
        if cfg.GARMIN_TOKEN_FILE.exists():
            cfg.GARMIN_TOKEN_FILE.unlink()
            log.info("  Token file removed")
    except Exception as e:
        log.warning(f"  Could not remove token file: {e}")
        ok = False

    _clear_token_dir()

    try:
        import keyring
        keyring.delete_password(KEYRING_SERVICE, KEYRING_ENC_USER)
        log.info("  Encryption key removed from WCM")
    except Exception as e:
        log.warning(f"  Could not remove enc_key from WCM: {e}")
        ok = False

    return ok


# ══════════════════════════════════════════════════════════════════════════════
#  Token event log — observation only, never affects the login flow
# ══════════════════════════════════════════════════════════════════════════════

def log_token_event(event: str, trigger: str, **extra) -> None:
    """
    Appends one entry to garmin_token_log.json (LOG_DIR). Best-effort — a
    logging failure must never affect the login flow itself, so all errors
    are caught and merely warned about.

    event   : "created" | "invalidated" | "blocked" | "valid"
              "blocked" does not mean the token was deleted — used for the
              429/403 rate-limit case, where the token is deliberately kept
              (see garmin_api.py Path 1). Keeping this separate from
              "invalidated" avoids skewing token-lifetime analysis. "valid"
              covers the silent success path — token still valid, no SSO
              needed (v1.6.5.7.1).
    trigger : "sso_login" | "rejected_by_garmin" | "enc_key_missing_wcm" |
              "manual_reset" | "rate_limited" | "token_reused"
    extra   : optional additional fields, e.g. exception_type=..., detail=...
              (detail should already be truncated by the caller — this
              function does not truncate).

    caller is read automatically from the GARMIN_SESSION_LOG_PREFIX ENV var
    (set by garmin_collector.main()'s various entry points, or explicitly
    by the three direct login() callers) — not a parameter, since every
    existing call site would otherwise need updating (v1.6.5.7.2).

    app_version is read from version.py if importable; falls back to
    "unknown" rather than raising, since this module has no other
    dependency on the app's version module.
    """
    import garmin_config as cfg
    try:
        import version
        app_version = version.APP_VERSION
    except Exception as e:
        app_version = "unknown"
        log.debug(f"  Could not read app_version from version.py: {e}")

    # Read directly from os.environ, not cfg.SESSION_LOG_PREFIX — the latter
    # is a module-level constant computed once at import time and would go
    # stale in T3 (shared process) without a matching importlib.reload(cfg)
    # at exactly the right moment. A direct read always reflects the
    # current process environment (v1.6.5.7.2).
    caller = os.environ.get("GARMIN_SESSION_LOG_PREFIX", "unknown")

    entry = {
        "ts":          datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "event":       event,
        "trigger":     trigger,
        "app_version": app_version,
        "caller":      caller,
        **extra,
    }

    try:
        log_file = cfg.LOG_DIR / "garmin_token_log.json"
        data = json.loads(log_file.read_text()) if log_file.exists() else {"events": []}
        data["events"].append(entry)
        cfg.LOG_DIR.mkdir(parents=True, exist_ok=True)

        # v1.6.5.8 — mixed serialization: "valid" events (routine, no error
        # payload) collapse to one compact line so a quick scan shows the
        # baseline at a glance. Every other event (created/invalidated/
        # blocked) keeps the original indent=2 multi-line block unchanged —
        # that multi-line shape is itself the visual break when something
        # other than a routine valid login shows up in the log.
        def _format_event(e: dict) -> str:
            if e.get("event") == "valid":
                return json.dumps(e, separators=(",", ":"))
            lines = json.dumps(e, indent=2).split("\n")
            return "\n".join([lines[0]] + ["    " + ln for ln in lines[1:]])

        event_blocks = [_format_event(e) for e in data["events"]]
        log_text = "{\n  \"events\": [\n    " + ",\n    ".join(event_blocks) + "\n  ]\n}"
        log_file.write_text(log_text)
    except Exception as e:
        log.warning(f"  Token event log write failed: {e}")


def has_unresolved_mfa_block() -> bool:
    """
    Read-side counterpart to log_token_event() — fail-open by design: an
    unreadable or malformed garmin_token_log.json returns False (no block)
    rather than blocking a login attempt over an observation-log problem,
    same best-effort principle as log_token_event() itself (v1.6.5.9).

    Scans events newest-first (the log is append-only, so reversed() is
    chronological-descending). Returns True if the most recent relevant
    event is a "blocked"/"mfa_required_no_callback" entry — a headless SSO
    attempt hit MFA with no interactive callback available — and no
    "created"/"sso_login" event (necessarily interactive, since that's the
    only way MFA gets resolved) has happened since. clear_token()/
    manual_reset does NOT clear this — a deleted token says nothing about
    whether the MFA problem itself is resolved; only a real successful SSO
    proves that.
    """
    import garmin_config as cfg
    try:
        log_file = cfg.LOG_DIR / "garmin_token_log.json"
        if not log_file.exists():
            return False
        data = json.loads(log_file.read_text())
        for entry in reversed(data.get("events", [])):
            if entry.get("event") == "created" and entry.get("trigger") == "sso_login":
                return False
            if entry.get("event") == "blocked" and entry.get("trigger") == "mfa_required_no_callback":
                return True
        return False
    except Exception as e:
        log.warning(f"  Token event log read failed — treating as no block: {e}")
        return False
